[package]
name = "threebodyproblem"
version = "0.1.0"
edition = "2024"

[dependencies]
plotters = "0.3"
egui = "0.27"
eframe = "0.27"
kiss3d = "0.31"
nalgebra = "0.32"
chrono = "0.4"
png = "0.17.16"
gif = "0.13.1"

