[package]
name = "linear_regression"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15"
ndarray-linalg = { version = "0.16", features = ["intel-mkl"] }
plotters = "0.3"
rand = "0.9.1"
rand_distr = "0.5.1"
